//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class FrienshipRequest
    {
        public int IdFriendshipRequest { get; set; }
        public int IdSenderPlayer { get; set; }
        public int IdReceiverPlayer { get; set; }
    
        public virtual Player SenderPlayer { get; set; }
        public virtual Player ReceiverPlayer { get; set; }
    }
}
